FROM ubuntu:latest

RUN apt-get update
RUN DEBIAN_FRONTEND="noninteractive" apt-get install apache2 -y php7.4 libapache2-mod-php7.4
RUN a2enmod php7.4

ENV APACHE_LOG_DIR /var/log/apache2

COPY index.html /var/www/html
EXPOSE 80

CMD apachectl -D FOREGROUND